export const state = [
    'Andaman and Nicobar Islands', 
    'Andhra Pradesh', 
    'Arunachal Pradesh', 
    'Assam', 
    'Bihar', 
    'Chandigarh', 
    'Chhattisgarh', 
    'Dadra and Nagar Haveli', 
    'Daman and Diu', 
    'Delhi', 
    'Goa', 
    'Gujarat', 
    'Haryana', 
    'Himachal Pradesh', 
    'Jammu', 
    'Jharkhand', 
    'Karnataka', 
    'Kashmir', 
    'Kerala', 
    'Ladakh', 
    'Lakshadweep', 
    'Madhya Pradesh', 
    'Maharashtra', 
    'Manipur', 
    'Meghalaya', 
    'Mizoram', 
    'Nagaland', 
    'Odisha', 
    'Puducherry', 
    'Punjab', 
    'Rajasthan', 
    'Sikkim', 
    'Tamil Nadu', 
    'Telangana', 
    'Tripura', 
    'Uttarakhand', 
    'Uttar Pradesh', 
    'West Bengal'
]


export const branchs = [
    'software_engineering',
    'electronics_engineering',
    'mechanical_engineering',
    'civil_engineering',
    'mba',
    'english_hons',
    "llb",
    "ba",
    "mbbs"
]